addons:
  ssh_known_hosts: russellhay.com

language: go
go:
- "1.10.x"
install:
  - go get -u -v github.com/spf13/hugo
script:
  - cd $GOPATH/src/github.com/stainlessio/hire
  - hugo

notifications:
  email:
    on_faliure: always

before_install:
- openssl aes-256-cbc -K $encrypted_d643588494ce_key -iv $encrypted_d643588494ce_iv -in deploy.rsa.enc -out deploy.rsa -d

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy.rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy.rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/hire/
  on:
    branch: master
